export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const DOWNLOAD_FILE_REQUEST = "DOWNLOAD_FILE_REQUEST"
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS"
export const DOWNLOAD_FILE_FAILURE = "DOWNLOAD_FILE_FAILURE"

export const DOWNLOAD_BULK_FILE_REQUEST = "DOWNLOAD_FILE_BULK_REQUEST";
export const DOWNLOAD_BULK_FILE_SUCCESS = "DOWNLOAD_FILE_BULK_SUCCESS";
export const DOWNLOAD_BULK_FILE_FAILURE = "DOWNLOAD_FILE_BULK_FAILURE";